version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: postgresDb
    ports:
      - 127.0.0.1:10000:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=comaNews